WCCIFinalProject/Models/ProjectData.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCCIFinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDataEntities : DbContext
    {
        public ProjectDataEntities()
            : base("name=ProjectDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProjectData> ProjectDatas { get; set; }
    }
}

WCCIFinalProject/Models/ProjectData.Designer.cs
// T4 code generation is enabled for model 'C:\Users\WeCanCodeIT\Documents\Visual Studio 2015\Projects\WCCIFinalProject\WCCIFinalProject\Models\ProjectData.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

WCCIFinalProject/Models/ProjectData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCCIFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectData
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string Language { get; set; }
        public string ImageLink { get; set; }
        public string GitHub { get; set; }
        public string Collaborators { get; set; }
    }
}

WCCIFinalProject/Models/ProjectData1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

WCCIFinalProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WCCIFinalProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "ABOUT ME TEXTTTT";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WCCIFinalProject/Controllers/ProjectDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WCCIFinalProject.Models;

namespace WCCIFinalProject.Controllers
{
    public class ProjectDatasController : Controller
    {
        private ProjectDataEntities db = new ProjectDataEntities();

        // GET: ProjectDatas
        public ActionResult Index()
        {
            return View(db.ProjectDatas.ToList());
        }

        // GET: ProjectDatas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectData projectData = db.ProjectDatas.Find(id);
            if (projectData == null)
            {
                return HttpNotFound();
            }
            return View(projectData);
        }

        // GET: ProjectDatas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectID,ProjectName,ProjectDescription,Language,ImageLink,GitHub,Collaborators")] ProjectData projectData)
        {
            if (ModelState.IsValid)
            {
                db.ProjectDatas.Add(projectData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projectData);
        }

        // GET: ProjectDatas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectData projectData = db.ProjectDatas.Find(id);
            if (projectData == null)
            {
                return HttpNotFound();
            }
            return View(projectData);
        }

        // POST: ProjectDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectID,ProjectName,ProjectDescription,Language,ImageLink,GitHub,Collaborators")] ProjectData projectData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projectData);
        }

        // GET: ProjectDatas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectData projectData = db.ProjectDatas.Find(id);
            if (projectData == null)
            {
                return HttpNotFound();
            }
            return View(projectData);
        }

        // POST: ProjectDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectData projectData = db.ProjectDatas.Find(id);
            db.ProjectDatas.Remove(projectData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WCCIFinalProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<body class="aboutBackground"> 
   
    <div class="container-fluid text-center">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Projects", "Index", "ProjectDatas")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        </div>

        <div class="container aboutContain">

            <div class="col-md-3">
                <img class="aboutPhoto" src="~/Content/Images/AboutMePhoto.jpg" />
            </div>

            <div class="col-md-6 col-md-offset-1 section">
                <h1 class="aboutH1">
                    About Me
                </h1>

                <div class="aboutParagraphs">
                    <p class="text-center col-xs-12">
                        Hi, my name's Scott.

                    </p>

                    <p class="aboutMePara col-xs-12">
                        I'm an aspiring software engineer and recent graduate from We Can {Code} IT, Coding Boot Camp.
                    </p>

                    <p class="col-xs-12">
                        Thus far, I am most familiar with C# and the .NET Framework. I have a basic understanding of SQL Server and Front-End Development (HTML / CSS / Bootstrap).
                        I'm eager to expand my basis of knowledge, and look forward to being apart of a team where I can grow and in turn utilize my skills to contribute to the development of your organization.
                        @*Although I am still finding my niche as a developer, I am very open to learning and eager to become a part of a team where I can grow and in turn utilize my skills to contribute to the development of your organization.*@
                    </p>

                </div>
            </div>






            @*<h2>@ViewBag.Title.</h2>
                <h3>@ViewBag.Message</h3>*@

WCCIFinalProject/Views/Home/Contact.cshtml
@*@{
    ViewBag.Title = "Contact";
}*@
@*<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@


<body class="contactBackground text-center" style="background-color:cadetblue"></body>

<div class="container-fluid text-center">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Projects", "Index", "ProjectDatas")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    
                    

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    </div>

    <h1 class="text-center contactH1">
        Contact Me
    </h1>

    <hr class="contact-line" />

   @* Contact Links *@
<div class="container socialmedia">

        <div class="col-md-3 gitHub">

            <a href="https://github.com/l1adan" target="_blank">
                <img class="contactIcons" src="~/Content/Images/git.png" />
                <p class="contactP">GitHub</p>
            </a>
            @*<a href="https://www.github.com/l1adan" class="gitDescript" target="_blank">
                <p class="gitDescript">Github</p>*@
            </a>
       </div>
       <div class="col-md-3 email">
           <a href="mailto:Scott.Ladan@gmail.com" class="email-img">
               <img width="115"class="contactIcons email-img" src="~/Content/Images/transMail.png" />
               <p class="contactP">Scott.Ladan@gmail.com</p>
           </a>
          
       </div>
       <div class="col-md-3">
           <a href="https://www.linkedin.com/in/scottladan" target="_blank">
                <img class="contactIcons" src="~/Content/Images/linkedInIcon.png" />
               <p class="contactP">LinkedIn</p>
           </a>
      </div> 
      <div class="col-md-3">
          <img class="contactIcons" src="~/Content/Images/phone.png" />
          <p class="contactP">216-904-5726</p>
      </div>

       </div>
       <hr class="contact-line container-fluid" />
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container-fluid">
            
        </div>
    </nav>

WCCIFinalProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<body class="front-page text-center">

    <div class="container-fluid">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      
                    </button>
                    
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    

                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Projects", "Index", "ProjectDatas")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        @*<li>@Html.ActionLink("temp","temp","Home")</li>*@
                        
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
 
    
        <div>
            <img class="coverPhoto" src="~/Content/Images/unnamed.jpg" />

        </div>
        <div class="cover inner">
            <h1 class="homeH1">SCOTT LADAN</h1>
            <h2>Developer</h2>
        </div>

        @*<nav class="navbar navbar-inverse navbar-fixed-bottom">
            <div class="container-fluid footy">
                
            </div>
        </nav>*@
  


        @*<div class="menu">

        </div>*@
           
            
         
            
            
            
            
            
            
            
             
               

WCCIFinalProject/Views/Home/temp.cshtml
@{
    ViewBag.Title = "temp";
}

<body class="OPAC"></body>

WCCIFinalProject/Views/ProjectDatas/Create.cshtml
@model WCCIFinalProject.Models.ProjectData

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GitHub, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GitHub, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GitHub, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Collaborators, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Collaborators, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Collaborators, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WCCIFinalProject/Views/ProjectDatas/Delete.cshtml
@model WCCIFinalProject.Models.ProjectData

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GitHub)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GitHub)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Collaborators)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Collaborators)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WCCIFinalProject/Views/ProjectDatas/Details.cshtml
@model WCCIFinalProject.Models.ProjectData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProjectData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GitHub)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GitHub)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Collaborators)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Collaborators)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProjectID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WCCIFinalProject/Views/ProjectDatas/Edit.cshtml
@model WCCIFinalProject.Models.ProjectData

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjectID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GitHub, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GitHub, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GitHub, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Collaborators, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Collaborators, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Collaborators, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WCCIFinalProject/Views/ProjectDatas/Index.cshtml
@model IEnumerable<WCCIFinalProject.Models.ProjectData>

@{
    ViewBag.Title = "Index";
}


<body class="ProjectsBackground"></body>

@*<p>
        @Html.ActionLink("create new", "create")
    </p>*@



    <div class="container-fluid text-center">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Projects", "Index", "ProjectDatas")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>


    <div class="container" style="overflow: hidden">


        @foreach (var item in Model)
            {
            <div class="project">
                <div class="col-sm-offset-3 col-sm-9 title">@item.ProjectName</div>

                <div class="col-sm-2">

                    <a target="_blank" href="@item.GitHub">
                        <img class="img-responsive" src="~/Content/Images/Octocat.png" />
                    </a>

                </div>
                <div class="col-sm-5">
                    <img class="img-responsive" src="@item.ImageLink" />

                </div>
                <div class="col-sm-5 description">
                    <p>@item.ProjectDescription</p>
                </div>

                @*@Html.DisplayFor(modelItem => item.Language)*@

                @*@Html.DisplayFor(modelItem => item.Collaborators)*@

                @*@Html.ActionLink("Edit", "Edit", new { id = item.ProjectID })
                    @Html.ActionLink("Details", "Details", new { id = item.ProjectID })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProjectID })*@


            </div>
           
        


        }

WCCIFinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scott Ladan | Portfolio</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/cover.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
</head>

    
        @RenderBody()
</div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script>
        $(document).ready(function () {
            $('.email').hover(function () {
                $('.email-address').fadeIn();
            },
            function() {
                $('.email-address').fadeOut();
            });

            $('.gitHub').hover(function () {
                $('.gitDescript').fadeIn();
            },
            function () {
                $('.gitDescript').fadeOut();
            });
        });
    </script>*@
    @RenderSection("scripts", required: false)
</body>
</html>